name: it_alem
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^5.0.4
  # async: ^2.9.0
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  collection: ^1.17.0
  convex_bottom_bar: ^3.1.0+1
  country_picker: ^2.0.19
  cupertino_icons: ^1.0.5
  # dartz: ^0.10.1 не должен использоваться
  dio: ^4.0.6
  # dotted_border: ^2.0.0+3
  drift: ^2.4.2
  dropdown_button2: ^1.9.2
  # easy_localization: ^3.0.1
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  extended_image: ^7.0.1
  # firebase_core: ^2.1.1
  # firebase_crashlytics: ^3.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_html: ^3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: # ^5.1.0
    git:
      url: https://github.com/Aboneyx/flutter_spinkit.git
      ref: 85688aed4263a801fa41a88da97c78ef89bb5509
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.1.3
  freezed_annotation:
  # get_it: ^7.2.0 не должен использоваться
  geolocator: ^9.0.2
  google_fonts: ^4.0.1
  grouped_list: ^5.1.2
  # html_editor_enhanced: ^2.2.0+1-dev.1
  image_picker: ^0.8.6+1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  l: ^3.2.0
  loader_overlay: ^2.1.0
  lottie: ^2.2.0
  mask_text_input_formatter: ^2.1.0
  meta: ^1.8.0
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.11
  pinput: ^2.2.21
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  pure: ^0.2.0
  rxdart: ^0.27.7
  scroll_to_index: ^3.0.1
  select_annotation: ^0.2.0
  # sentry_flutter: ^6.14.0
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.12
  stack_trace: ^1.11.0
  stream_bloc: ^0.5.3
  timelines: ^0.1.0
  url_launcher: ^6.1.9

dev_dependencies:
  auto_route_generator: ^5.0.3
  # bloc_test: ^9.0.3
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  # dart_code_metrics: ^4.16.0
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  freezed: ^2.3.2
  lint: ^2.0.1
  # mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
